# Generated by Django 5.0.6 on 2025-09-08 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'history_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryLogTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'history_log_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=12)),
                ('notification_type', models.CharField(max_length=20)),
                ('notification_timestamp', models.DateTimeField()),
                ('is_read', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductBatches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('manufactured_date', models.DateField()),
                ('expiration_date', models.DateField()),
            ],
            options={
                'db_table': 'product_batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRecipes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'product_recipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_variants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterialBatches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_material_batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size_label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sizes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SizeUnits',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'size_units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SrpPrices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('srp_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'srp_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockChanges',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=12)),
                ('item_id', models.BigIntegerField()),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'stock_changes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitPrices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'unit_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=12)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'withdrawals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='realsproj.products')),
                ('total_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restock_threshold', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'product_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterialInventory',
            fields=[
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='realsproj.rawmaterials')),
                ('total_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'raw_material_inventory',
                'managed': False,
            },
        ),
    ]
