# Generated by Django 5.0.6 on 2025-09-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realsproj', '0002_alter_expenses_options_alter_historylog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='historylog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='historylogtypes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productbatches',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productinventory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productrecipes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producttypes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productvariants',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rawmaterialbatches',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rawmaterialinventory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rawmaterials',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sizes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sizeunits',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='srpprices',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stockchanges',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='unitprices',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='withdrawals',
            options={'managed': False},
        ),
    ]
