# Generated by Django 5.0.6 on 2025-09-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realsproj', '0003_alter_expenses_options_alter_historylog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesSummary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'expenses_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'sales_summary',
                'managed': False,
            },
        ),
    ]
