# Generated by Django 5.0.6 on 2025-09-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realsproj', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': False},
        ),
    ]
