# Generated by Django 5.0.6 on 2025-10-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realsproj', '0007_alter_productrecipes_options_discounts_useractivity_and_more'),
    ]

    operations = [
    ]
